/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "ChatSystemAWSAmplify",
            "endpoint": "https://14tucvi35f.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-southeast-1:e78e1ced-4b37-4977-8c47-d59ac2d1dd45",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_eZt19Hh46",
    "aws_user_pools_web_client_id": "fph89s6l1e2cav1oo8qapjogq",
    "oauth": {},
    "aws_user_files_s3_bucket": "awsamplifystorage155937-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
